const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.jumpthru,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.Pin,
		C3.Behaviors.Physics,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.Camera3D,
		C3.Behaviors.bound,
		C3.Plugins.Browser,
		C3.Behaviors.Fade,
		C3.Behaviors.Tween,
		C3.Behaviors.NoSave,
		C3.Behaviors.shadowcaster,
		C3.Behaviors.Persist,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Exps.left,
		C3.Plugins.Audio.Acts.Seek,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Cnds.CompareFrameTag,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.time,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.System.Acts.ScrollToObject,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.CompareFrame
	];
};
self.C3_JsPropNameTable = [
	{Bg1SkyDay: 0},
	{Bg2Far: 0},
	{Bg3Middle: 0},
	{Bg5Close: 0},
	{River: 0},
	{Plane: 0},
	{Platformmove1: 0},
	{PlatformMove: 0},
	{Jumpthru: 0},
	{PlatformLE: 0},
	{Solid: 0},
	{PlatformRE: 0},
	{PlankRE: 0},
	{PlankLE: 0},
	{PlankM: 0},
	{PlatformM: 0},
	{"1BarrelRound": 0},
	{"3BarrelRound": 0},
	{TankYellow: 0},
	{TankOrange: 0},
	{Fish: 0},
	{FishUp: 0},
	{FishDown: 0},
	{Tree1BG: 0},
	{Tree1: 0},
	{Tree2BG: 0},
	{Tree2: 0},
	{Tree3BG: 0},
	{Tree3: 0},
	{Shack1BG: 0},
	{Shack1BGFar: 0},
	{Shack1: 0},
	{Shack2BG: 0},
	{Shack2BGFar: 0},
	{Shack3: 0},
	{Shack4: 0},
	{Bg2SkyNight: 0},
	{PlayersLives: 0},
	{IsClimbing: 0},
	{State: 0},
	{IsZiplining: 0},
	{ZipSpeed: 0},
	{ZipTargetX: 0},
	{ZipTargetY: 0},
	{ZipEase: 0},
	{IsZiplining2: 0},
	{Invincible: 0},
	{Platform: 0},
	{Pin: 0},
	{Physics: 0},
	{ScrollTo: 0},
	{Player: 0},
	{Poles2Bg: 0},
	{Poles1Bg: 0},
	{PoleSingleBg: 0},
	{PoleSingle: 0},
	{PlatformLPoles1Bg: 0},
	{PlatformRPoles1Bg: 0},
	{PlatformMPoles1Bg: 0},
	{Hook: 0},
	{Tank3: 0},
	{LaderLBg: 0},
	{LadderRBg: 0},
	{LaderL: 0},
	{LadderR: 0},
	{RopePos: 0},
	{RopeNeg: 0},
	{Crate1: 0},
	{Boatwithrafts: 0},
	{Crate2: 0},
	{Crate3Guns: 0},
	{Boat2: 0},
	{Buoy2: 0},
	{BoxSetRed: 0},
	{BoxSetGreen: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Croc: 0},
	{Crateguns: 0},
	{RestOfHook: 0},
	{CrocMove: 0},
	{Croc1: 0},
	{Hearts: 0},
	{StartY: 0},
	{Coin: 0},
	{BoundShack: 0},
	{InsideShack1: 0},
	{Tree1Door: 0},
	{mountedCandleFlicker: 0},
	{Invisiblefloor1: 0},
	{Outer: 0},
	{blackfillerL3: 0},
	{Spawn_InsideTree: 0},
	{Tree4: 0},
	{Sign1: 0},
	{WLader: 0},
	{waterDie: 0},
	{Audio: 0},
	{BoatZone: 0},
	{Sprite: 0},
	{Tree1DoorCLONE: 0},
	{raft1: 0},
	{HangingPlatformG: 0},
	{HangingPlatformGCLONE: 0},
	{hangingplatformADDON: 0},
	{hangingplatformADDONCLONE: 0},
	{candleFlicker: 0},
	{CandleFLicker3: 0},
	{CandleFlicker2: 0},
	{Screenshot20260421At22136pm: 0},
	{Screenshot20260421At22604pm: 0},
	{Key: 0},
	{KeyGlow: 0},
	{Sprite3: 0},
	{ladderpiece: 0},
	{Sprite4: 0},
	{Sine: 0},
	{HangingPlatformG2: 0},
	{hangingplatformADDON2: 0},
	{Portal_ToTree: 0},
	{soildTets: 0},
	{Portal_ExitTree: 0},
	{Spawn_WaterArea: 0},
	{Screenshot20260423At111227am: 0},
	{LadderR2: 0},
	{HangingPlatformG3: 0},
	{hangingplatformADDON3: 0},
	{TiledBackground: 0},
	{Gate1: 0},
	{Gate2: 0},
	{Vines1: 0},
	{Vines2: 0},
	{Vines3: 0},
	{Vines4: 0},
	{Vines5: 0},
	{Vines6: 0},
	{Vines7: 0},
	{Vines8: 0},
	{Vines9: 0},
	{Vines10: 0},
	{HasLanded: 0},
	{HasSpoken: 0},
	{Typing: 0},
	{TextIndex: 0},
	{FinishSpeaking: 0},
	{isFlying: 0},
	{Bird: 0},
	{VinesPerch: 0},
	{SpeechBubble1: 0},
	{LadderRBg2: 0},
	{BirdText: 0},
	{Croc2: 0},
	{ChatGPTImageApr24202612_19_04PM: 0},
	{CF1Shack: 0},
	{Screenshot20260424At122221pm: 0},
	{CF2Shack: 0},
	{Screenshot20260424At123202pm: 0},
	{ChestOpen1: 0},
	{ChestOpen2: 0},
	{ChestOpen3: 0},
	{ChestOpen4: 0},
	{ChestOpen5: 0},
	{ChestOpen6: 0},
	{Opened: 0},
	{ChestSpriteSheet: 0},
	{ShackRoof: 0},
	{Portal_ToShack1: 0},
	{Spawn_Shack_Inside: 0},
	{SHackinsideclone: 0},
	{Bg1SkyDayCLONE: 0},
	{CLONEMplatform: 0},
	{PlatformLPoles1Bg2: 0},
	{PlatformMPoles1Bg2: 0},
	{Portal_ExitShack1: 0},
	{Sprite2: 0},
	{ExitShackSP1: 0},
	{PortalExitShack2: 0},
	{Portal_ToShack2: 0},
	{Screenshot20260425At121647pm: 0},
	{BirdTarget: 0},
	{BirdTrigger: 0},
	{BedInL2: 0},
	{ChatGPTImageApr28202607_40_25PM: 0},
	{FloorofL2: 0},
	{Cratestopper: 0},
	{Sprite6: 0},
	{River2: 0},
	{BirdMessage: 0},
	{BirdEarly: 0},
	{BirdTriggerEarly: 0},
	{SpeechBubbleEarly: 0},
	{BirdTextEarly: 0},
	{VinesPerchEarly: 0},
	{BirdTargetEarly: 0},
	{Torch: 0},
	{NightOverlay: 0},
	{TorchCone: 0},
	{Sprite7: 0},
	{TiledBackground2: 0},
	{SunsetOverlay: 0},
	{GrassTB: 0},
	{GT1: 0},
	{Sprite8: 0},
	{DangerSign: 0},
	{DangerSign2: 0},
	{Monster: 0},
	{MonsterTrigger: 0},
	{Tree5: 0},
	{TiledBackground3: 0},
	{MenupageMainDesign: 0},
	{videofloor: 0},
	{videoplayer: 0},
	{temple: 0},
	{Temple2: 0},
	{Enemymove: 0},
	{Snake: 0},
	{LadderR3: 0},
	{Bg3Middle2: 0},
	{MenuP: 0},
	{PlayButton: 0},
	{OptionsButton: 0},
	{Bg5Close2: 0},
	{Bg3Middle3: 0},
	{Bg2Far2: 0},
	{TiledBackground4: 0},
	{woodenBoard: 0},
	{OptionsButton2: 0},
	{"3DCamera": 0},
	{ZipStart: 0},
	{ZipEnd: 0},
	{ZipHandle: 0},
	{ChatGPTImageJun29202608_09_42PM: 0},
	{InventoryBox: 0},
	{ItemSlot1: 0},
	{EquipButton: 0},
	{CollectibleItem1: 0},
	{ItemIcon1: 0},
	{ItemSlot2: 0},
	{ItemSlot3: 0},
	{SelectedSlotOutline: 0},
	{EquippedItem1: 0},
	{CollectibleItem2: 0},
	{EquippedItem2: 0},
	{ItemIcon2: 0},
	{CollectibleItem3: 0},
	{EquippedItem3: 0},
	{ItemIcon3: 0},
	{ChatGPTImageJul1202609_23_54AM: 0},
	{ChatGPTImageJul1202609_28_34AM: 0},
	{ChatGPTImageJul1202609_35_55AM: 0},
	{selectedOutline: 0},
	{Collected: 0},
	{KeyIcon: 0},
	{KeyEquipped: 0},
	{TorchIcon: 0},
	{TorchEquipped: 0},
	{Zipline: 0},
	{ZiplineEquipped: 0},
	{ZiplineIcon: 0},
	{Lantern: 0},
	{EndingCity: 0},
	{CoinText: 0},
	{Coin2: 0},
	{PlatformLE2: 0},
	{Sprite5: 0},
	{ZipStart2: 0},
	{ZipEnd2: 0},
	{e9c84ab8ec68483b8cece4026c305ffe: 0},
	{BoundTo: 0},
	{TiledBackground5: 0},
	{TiledBackground6: 0},
	{TiledBackground7: 0},
	{Sprite9: 0},
	{PortalToLayout3: 0},
	{Layout3Spawn: 0},
	{Browser: 0},
	{PlatformRE2: 0},
	{PlatformLE3: 0},
	{Zip1Rope: 0},
	{LaderLBg2: 0},
	{Sprite10: 0},
	{Boat3: 0},
	{Boat: 0},
	{BoatEnterZone: 0},
	{BoatExitSpawn: 0},
	{BoatExit: 0},
	{Sprite11: 0},
	{BoatEndPosition: 0},
	{NightRiver: 0},
	{Sprite12: 0},
	{GateFloor: 0},
	{GateGlow: 0},
	{GateGlow2: 0},
	{Sprite13: 0},
	{FireStand2: 0},
	{ChatGPTImageJul23202607_43_45PM: 0},
	{ChatGPTImageJul23202607_44_28PM: 0},
	{FireStand1: 0},
	{FireStand3: 0},
	{FireStand4: 0},
	{FlameCone1: 0},
	{FlameCone2: 0},
	{GateGlow3: 0},
	{GateGlow4: 0},
	{GateOpenLeft: 0},
	{GateOpen2: 0},
	{Gate3: 0},
	{GateOpen3: 0},
	{GateOpen4: 0},
	{GateOpen4experi: 0},
	{GateOpen4experi2: 0},
	{GateOpenRight: 0},
	{GateTrigger: 0},
	{Fade: 0},
	{Tween: 0},
	{FadeBlack: 0},
	{Crate3: 0},
	{Checkpoint: 0},
	{BoatSign: 0},
	{leftarrow: 0},
	{Sprite14: 0},
	{InteractionPrompt1: 0},
	{InteractionPrompt2: 0},
	{ZiplinePrompt: 0},
	{InteractionPrompt3: 0},
	{Prompttrigger: 0},
	{InteractionPrompt4: 0},
	{KeyTrigger: 0},
	{EndingFade: 0},
	{EndingText: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{GateGlow5: 0},
	{GateGlow6: 0},
	{GateGlow7: 0},
	{GateGlow8: 0},
	{GateGlow9: 0},
	{NoSave: 0},
	{ShadowCaster: 0},
	{Persist: 0},
	{Sprite17: 0},
	{ChatGPTImageJul28202610_21_33PM: 0},
	{ChatGPTImageJul28202610_26_56PM: 0},
	{BoatWharfSpawn: 0},
	{BWDie1: 0},
	{Sprite18: 0},
	{ExitToMenu: 0},
	{Sprite19: 0},
	{Family1: 0},
	{NextSpawnX: 0},
	{NextSpawnY: 0},
	{UseSpawn: 0},
	{FullBirdText: 0},
	{FullBirdTextEarly: 0},
	{InventoryOpen: 0},
	{HasItem1: 0},
	{Item1Equipped: 0},
	{SelectedSlot: 0},
	{HasItem2: 0},
	{HasItem3: 0},
	{EquippedItem: 0},
	{CoinCount: 0},
	{ComingFromLayout1: 0},
	{CheckpointX: 0},
	{CheckpointY: 0},
	{CheckpointLayout: 0},
	{HasKey: 0},
	{HasTorch: 0},
	{TorchIsEquipped: 0},
	{IsInBoat: 0},
	{BoatFinished: 0},
	{GateHasOpened: 0},
	{GateIsFading: 0},
	{EndingFadingIn: 0},
	{EndingFadingOut: 0}
];

self.InstanceType = {
	Bg1SkyDay: class extends self.ITiledBackgroundInstance {},
	Bg2Far: class extends self.ITiledBackgroundInstance {},
	Bg3Middle: class extends self.ITiledBackgroundInstance {},
	Bg5Close: class extends self.ITiledBackgroundInstance {},
	River: class extends self.ITiledBackgroundInstance {},
	Plane: class extends self.ISpriteInstance {},
	PlatformLE: class extends self.ISpriteInstance {},
	PlatformRE: class extends self.ISpriteInstance {},
	PlankRE: class extends self.ISpriteInstance {},
	PlankLE: class extends self.ISpriteInstance {},
	PlankM: class extends self.ISpriteInstance {},
	PlatformM: class extends self.ISpriteInstance {},
	_1BarrelRound: class extends self.ISpriteInstance {},
	_3BarrelRound: class extends self.ISpriteInstance {},
	TankYellow: class extends self.ISpriteInstance {},
	TankOrange: class extends self.ISpriteInstance {},
	Fish: class extends self.ISpriteInstance {},
	FishUp: class extends self.ISpriteInstance {},
	FishDown: class extends self.ISpriteInstance {},
	Tree1BG: class extends self.ISpriteInstance {},
	Tree1: class extends self.ISpriteInstance {},
	Tree2BG: class extends self.ISpriteInstance {},
	Tree2: class extends self.ISpriteInstance {},
	Tree3BG: class extends self.ISpriteInstance {},
	Tree3: class extends self.ISpriteInstance {},
	Shack1BG: class extends self.ISpriteInstance {},
	Shack1BGFar: class extends self.ISpriteInstance {},
	Shack1: class extends self.ISpriteInstance {},
	Shack2BG: class extends self.ISpriteInstance {},
	Shack2BGFar: class extends self.ISpriteInstance {},
	Shack3: class extends self.ISpriteInstance {},
	Shack4: class extends self.ISpriteInstance {},
	Bg2SkyNight: class extends self.ITiledBackgroundInstance {},
	Player: class extends self.ISpriteInstance {},
	Poles2Bg: class extends self.ISpriteInstance {},
	Poles1Bg: class extends self.ISpriteInstance {},
	PoleSingleBg: class extends self.ISpriteInstance {},
	PoleSingle: class extends self.ISpriteInstance {},
	PlatformLPoles1Bg: class extends self.ISpriteInstance {},
	PlatformRPoles1Bg: class extends self.ISpriteInstance {},
	PlatformMPoles1Bg: class extends self.ISpriteInstance {},
	Hook: class extends self.ISpriteInstance {},
	Tank3: class extends self.ISpriteInstance {},
	LaderLBg: class extends self.ISpriteInstance {},
	LadderRBg: class extends self.ISpriteInstance {},
	LaderL: class extends self.ISpriteInstance {},
	LadderR: class extends self.ISpriteInstance {},
	RopePos: class extends self.ISpriteInstance {},
	RopeNeg: class extends self.ISpriteInstance {},
	Crate1: class extends self.ISpriteInstance {},
	Boatwithrafts: class extends self.ISpriteInstance {},
	Crate2: class extends self.ISpriteInstance {},
	Crate3Guns: class extends self.ISpriteInstance {},
	Boat2: class extends self.ISpriteInstance {},
	Buoy2: class extends self.ISpriteInstance {},
	BoxSetRed: class extends self.ISpriteInstance {},
	BoxSetGreen: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Croc: class extends self.ISpriteInstance {},
	Crateguns: class extends self.ISpriteInstance {},
	RestOfHook: class extends self.ISpriteInstance {},
	Croc1: class extends self.ISpriteInstance {},
	Hearts: class extends self.ISpriteInstance {},
	Coin: class extends self.ISpriteInstance {},
	BoundShack: class extends self.ISpriteInstance {},
	InsideShack1: class extends self.ISpriteInstance {},
	Tree1Door: class extends self.ISpriteInstance {},
	mountedCandleFlicker: class extends self.ISpriteInstance {},
	Invisiblefloor1: class extends self.ISpriteInstance {},
	Outer: class extends self.ISpriteInstance {},
	blackfillerL3: class extends self.ISpriteInstance {},
	Spawn_InsideTree: class extends self.ISpriteInstance {},
	Tree4: class extends self.ISpriteInstance {},
	Sign1: class extends self.ISpriteInstance {},
	WLader: class extends self.ISpriteInstance {},
	waterDie: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	BoatZone: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Tree1DoorCLONE: class extends self.ISpriteInstance {},
	raft1: class extends self.ISpriteInstance {},
	HangingPlatformG: class extends self.ISpriteInstance {},
	HangingPlatformGCLONE: class extends self.ISpriteInstance {},
	hangingplatformADDON: class extends self.ISpriteInstance {},
	hangingplatformADDONCLONE: class extends self.ISpriteInstance {},
	candleFlicker: class extends self.ISpriteInstance {},
	CandleFLicker3: class extends self.ISpriteInstance {},
	CandleFlicker2: class extends self.ISpriteInstance {},
	Screenshot20260421At22136pm: class extends self.ISpriteInstance {},
	Screenshot20260421At22604pm: class extends self.ISpriteInstance {},
	Key: class extends self.ISpriteInstance {},
	KeyGlow: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	ladderpiece: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	HangingPlatformG2: class extends self.ISpriteInstance {},
	hangingplatformADDON2: class extends self.ISpriteInstance {},
	Portal_ToTree: class extends self.ISpriteInstance {},
	soildTets: class extends self.ISpriteInstance {},
	Portal_ExitTree: class extends self.ISpriteInstance {},
	Spawn_WaterArea: class extends self.ISpriteInstance {},
	Screenshot20260423At111227am: class extends self.ISpriteInstance {},
	LadderR2: class extends self.ISpriteInstance {},
	HangingPlatformG3: class extends self.ISpriteInstance {},
	hangingplatformADDON3: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Gate1: class extends self.ISpriteInstance {},
	Gate2: class extends self.ISpriteInstance {},
	Vines1: class extends self.ISpriteInstance {},
	Vines2: class extends self.ISpriteInstance {},
	Vines3: class extends self.ISpriteInstance {},
	Vines4: class extends self.ISpriteInstance {},
	Vines5: class extends self.ISpriteInstance {},
	Vines6: class extends self.ISpriteInstance {},
	Vines7: class extends self.ISpriteInstance {},
	Vines8: class extends self.ISpriteInstance {},
	Vines9: class extends self.ISpriteInstance {},
	Vines10: class extends self.ISpriteInstance {},
	Bird: class extends self.ISpriteInstance {},
	VinesPerch: class extends self.ISpriteInstance {},
	SpeechBubble1: class extends self.ISpriteInstance {},
	LadderRBg2: class extends self.ISpriteInstance {},
	BirdText: class extends self.ITextInstance {},
	Croc2: class extends self.ISpriteInstance {},
	ChatGPTImageApr24202612_19_04PM: class extends self.ISpriteInstance {},
	CF1Shack: class extends self.ISpriteInstance {},
	Screenshot20260424At122221pm: class extends self.ISpriteInstance {},
	CF2Shack: class extends self.ISpriteInstance {},
	Screenshot20260424At123202pm: class extends self.ISpriteInstance {},
	ChestOpen1: class extends self.ISpriteInstance {},
	ChestOpen2: class extends self.ISpriteInstance {},
	ChestOpen3: class extends self.ISpriteInstance {},
	ChestOpen4: class extends self.ISpriteInstance {},
	ChestOpen5: class extends self.ISpriteInstance {},
	ChestOpen6: class extends self.ISpriteInstance {},
	ChestSpriteSheet: class extends self.ISpriteInstance {},
	ShackRoof: class extends self.ISpriteInstance {},
	Portal_ToShack1: class extends self.ISpriteInstance {},
	Spawn_Shack_Inside: class extends self.ISpriteInstance {},
	SHackinsideclone: class extends self.ISpriteInstance {},
	Bg1SkyDayCLONE: class extends self.ITiledBackgroundInstance {},
	CLONEMplatform: class extends self.ISpriteInstance {},
	PlatformLPoles1Bg2: class extends self.ISpriteInstance {},
	PlatformMPoles1Bg2: class extends self.ISpriteInstance {},
	Portal_ExitShack1: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	ExitShackSP1: class extends self.ISpriteInstance {},
	PortalExitShack2: class extends self.ISpriteInstance {},
	Portal_ToShack2: class extends self.ISpriteInstance {},
	Screenshot20260425At121647pm: class extends self.ISpriteInstance {},
	BirdTarget: class extends self.ISpriteInstance {},
	BirdTrigger: class extends self.ISpriteInstance {},
	BedInL2: class extends self.ISpriteInstance {},
	ChatGPTImageApr28202607_40_25PM: class extends self.ISpriteInstance {},
	FloorofL2: class extends self.ISpriteInstance {},
	Cratestopper: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	River2: class extends self.ITiledBackgroundInstance {},
	BirdEarly: class extends self.ISpriteInstance {},
	BirdTriggerEarly: class extends self.ISpriteInstance {},
	SpeechBubbleEarly: class extends self.ISpriteInstance {},
	BirdTextEarly: class extends self.ITextInstance {},
	VinesPerchEarly: class extends self.ISpriteInstance {},
	BirdTargetEarly: class extends self.ISpriteInstance {},
	Torch: class extends self.ISpriteInstance {},
	NightOverlay: class extends self.ISpriteInstance {},
	TorchCone: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	SunsetOverlay: class extends self.ISpriteInstance {},
	GrassTB: class extends self.ITiledBackgroundInstance {},
	GT1: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	DangerSign: class extends self.ISpriteInstance {},
	DangerSign2: class extends self.ISpriteInstance {},
	Monster: class extends self.ISpriteInstance {},
	MonsterTrigger: class extends self.ISpriteInstance {},
	Tree5: class extends self.ISpriteInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	MenupageMainDesign: class extends self.ISpriteInstance {},
	videofloor: class extends self.ISpriteInstance {},
	videoplayer: class extends self.ISpriteInstance {},
	temple: class extends self.ISpriteInstance {},
	Temple2: class extends self.ISpriteInstance {},
	Snake: class extends self.ISpriteInstance {},
	LadderR3: class extends self.ISpriteInstance {},
	Bg3Middle2: class extends self.ITiledBackgroundInstance {},
	MenuP: class extends self.ISpriteInstance {},
	PlayButton: class extends self.ISpriteInstance {},
	OptionsButton: class extends self.ISpriteInstance {},
	Bg5Close2: class extends self.ITiledBackgroundInstance {},
	Bg3Middle3: class extends self.ITiledBackgroundInstance {},
	Bg2Far2: class extends self.ITiledBackgroundInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	woodenBoard: class extends self.ISpriteInstance {},
	OptionsButton2: class extends self.ISpriteInstance {},
	_3DCamera: class extends self.IInstance {},
	ZipStart: class extends self.ISpriteInstance {},
	ZipEnd: class extends self.ISpriteInstance {},
	ZipHandle: class extends self.ISpriteInstance {},
	ChatGPTImageJun29202608_09_42PM: class extends self.ISpriteInstance {},
	InventoryBox: class extends self.ISpriteInstance {},
	ItemSlot1: class extends self.ISpriteInstance {},
	EquipButton: class extends self.ISpriteInstance {},
	CollectibleItem1: class extends self.ISpriteInstance {},
	ItemIcon1: class extends self.ISpriteInstance {},
	ItemSlot2: class extends self.ISpriteInstance {},
	ItemSlot3: class extends self.ISpriteInstance {},
	SelectedSlotOutline: class extends self.ISpriteInstance {},
	EquippedItem1: class extends self.ISpriteInstance {},
	CollectibleItem2: class extends self.ISpriteInstance {},
	EquippedItem2: class extends self.ISpriteInstance {},
	ItemIcon2: class extends self.ISpriteInstance {},
	CollectibleItem3: class extends self.ISpriteInstance {},
	EquippedItem3: class extends self.ISpriteInstance {},
	ItemIcon3: class extends self.ISpriteInstance {},
	ChatGPTImageJul1202609_23_54AM: class extends self.ISpriteInstance {},
	ChatGPTImageJul1202609_28_34AM: class extends self.ISpriteInstance {},
	ChatGPTImageJul1202609_35_55AM: class extends self.ISpriteInstance {},
	selectedOutline: class extends self.ISpriteInstance {},
	KeyIcon: class extends self.ISpriteInstance {},
	KeyEquipped: class extends self.ISpriteInstance {},
	TorchIcon: class extends self.ISpriteInstance {},
	TorchEquipped: class extends self.ISpriteInstance {},
	Zipline: class extends self.ISpriteInstance {},
	ZiplineEquipped: class extends self.ISpriteInstance {},
	ZiplineIcon: class extends self.ISpriteInstance {},
	Lantern: class extends self.ISpriteInstance {},
	EndingCity: class extends self.ISpriteInstance {},
	CoinText: class extends self.ITextInstance {},
	Coin2: class extends self.ISpriteInstance {},
	PlatformLE2: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	ZipStart2: class extends self.ISpriteInstance {},
	ZipEnd2: class extends self.ISpriteInstance {},
	e9c84ab8ec68483b8cece4026c305ffe: class extends self.ISpriteInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	TiledBackground6: class extends self.ITiledBackgroundInstance {},
	TiledBackground7: class extends self.ITiledBackgroundInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	PortalToLayout3: class extends self.ISpriteInstance {},
	Layout3Spawn: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	PlatformRE2: class extends self.ISpriteInstance {},
	PlatformLE3: class extends self.ISpriteInstance {},
	Zip1Rope: class extends self.ISpriteInstance {},
	LaderLBg2: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Boat3: class extends self.ISpriteInstance {},
	Boat: class extends self.ISpriteInstance {},
	BoatEnterZone: class extends self.ISpriteInstance {},
	BoatExitSpawn: class extends self.ISpriteInstance {},
	BoatExit: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	BoatEndPosition: class extends self.ISpriteInstance {},
	NightRiver: class extends self.ITiledBackgroundInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	GateFloor: class extends self.ISpriteInstance {},
	GateGlow: class extends self.ISpriteInstance {},
	GateGlow2: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	FireStand2: class extends self.ISpriteInstance {},
	ChatGPTImageJul23202607_43_45PM: class extends self.ISpriteInstance {},
	ChatGPTImageJul23202607_44_28PM: class extends self.ISpriteInstance {},
	FireStand1: class extends self.ISpriteInstance {},
	FireStand3: class extends self.ISpriteInstance {},
	FireStand4: class extends self.ISpriteInstance {},
	FlameCone1: class extends self.ISpriteInstance {},
	FlameCone2: class extends self.ISpriteInstance {},
	GateGlow3: class extends self.ISpriteInstance {},
	GateGlow4: class extends self.ISpriteInstance {},
	GateOpenLeft: class extends self.ISpriteInstance {},
	GateOpen2: class extends self.ISpriteInstance {},
	Gate3: class extends self.ISpriteInstance {},
	GateOpen3: class extends self.ISpriteInstance {},
	GateOpen4: class extends self.ISpriteInstance {},
	GateOpen4experi: class extends self.ISpriteInstance {},
	GateOpen4experi2: class extends self.ISpriteInstance {},
	GateOpenRight: class extends self.ISpriteInstance {},
	GateTrigger: class extends self.ISpriteInstance {},
	FadeBlack: class extends self.ISpriteInstance {},
	Crate3: class extends self.ISpriteInstance {},
	Checkpoint: class extends self.ISpriteInstance {},
	BoatSign: class extends self.ISpriteInstance {},
	leftarrow: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	InteractionPrompt1: class extends self.ITextInstance {},
	InteractionPrompt2: class extends self.ITextInstance {},
	ZiplinePrompt: class extends self.ISpriteInstance {},
	InteractionPrompt3: class extends self.ITextInstance {},
	Prompttrigger: class extends self.ISpriteInstance {},
	InteractionPrompt4: class extends self.ITextInstance {},
	KeyTrigger: class extends self.ISpriteInstance {},
	EndingFade: class extends self.ISpriteInstance {},
	EndingText: class extends self.ITextInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	GateGlow5: class extends self.ISpriteInstance {},
	GateGlow6: class extends self.ISpriteInstance {},
	GateGlow7: class extends self.ISpriteInstance {},
	GateGlow8: class extends self.ISpriteInstance {},
	GateGlow9: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	ChatGPTImageJul28202610_21_33PM: class extends self.ISpriteInstance {},
	ChatGPTImageJul28202610_26_56PM: class extends self.ISpriteInstance {},
	BoatWharfSpawn: class extends self.ISpriteInstance {},
	BWDie1: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	ExitToMenu: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Family1: class extends self.ISpriteInstance {}
}